spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse_test
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        check_nullability: true

#JWT
app:
  jwt-secret: JWTSecretKey
  jwt-expiration-milliseconds: 86400000